#pragma once

#include <string>
#include <iostream>
#include <ctime>
#include "Juego.h"

class Juego;

using namespace System;
using namespace System::Drawing;
using namespace std;

class Grafico
{
private:
    int iniciar;
    int niveles;
    int ayuda;
    int creditos;
    int salir;
    Juego* juego;
    void gotoXY(int x, int y);
    void dibujarLineaH(int x, int y, int tam);
    void dibujarLineaIncompleta(int x, int y, int tamanho);
    void dibujarRectanguloHueco(int x, int y, int largo, int ancho);
    void dibujarletraA(int x, int y);
    void dibujarletraB(int x, int y);
    void dibujarletraC(int x, int y);
    void dibujarletraD(int x, int y);
    void dibujarletraE(int x, int y);
    void dibujarletraF(int x, int y);
    void dibujarletraG(int x, int y);
    void dibujarletraH(int x, int y);
    void dibujarletraI(int x, int y);
    void dibujarletraJ(int x, int y);
    void dibujarletraK(int x, int y);
    void dibujarletraL(int x, int y);
    void dibujarletraM(int x, int y);
    void dibujarletraN(int x, int y);
    void dibujarletraO(int x, int y);
    void dibujarletraP(int x, int y);
    void dibujarletraQ(int x, int y);
    void dibujarletraR(int x, int y);
    void dibujarletraS(int x, int y);
    void dibujarletraT(int x, int y);
    void dibujarletraU(int x, int y);
    void dibujarletraV(int x, int y);
    void dibujarletraW(int x, int y);
    void dibujarletraX(int x, int y);
    void dibujarletraY(int x, int y);
    void dibujarletraZ(int x, int y);

    void dibujarnumero0(int x, int y);
    void dibujarnumero1(int x, int y);
    void dibujarnumero2(int x, int y);
    void dibujarnumero3(int x, int y);
    void dibujarnumero4(int x, int y);
    void dibujarnumero5(int x, int y);
    void dibujarnumero6(int x, int y);
    void dibujarnumero7(int x, int y);
    void dibujarnumero8(int x, int y);
    void dibujarnumero9(int x, int y);

    void flechitajsjsjs(int x, int y);
    void borrarflechitajsjsjs(int x, int y);
    void fleschitajsjajsja(int x, int y);
    void borrar_fleschitajsjajsja(int x, int y);
    void dibujarparentesisabierto(int x, int y);
    void dibujarparentesiscerrado(int x, int y);

    void number9(int x, int y);
    void number8(int x, int y);
    void number7(int x, int y);
    void number6(int x, int y);
    void number5(int x, int y);
    void number4(int x, int y);
    void number3(int x, int y);
    void number2(int x, int y);
    void number1(int x, int y);
    void number0(int x, int y);

    void dibujarnumeroMejor0(int x, int y);
    void dibujarnumeroMejor1(int x, int y);
    void dibujarnumeroMejor2(int x, int y);
    void dibujarnumeroMejor3(int x, int y);
    void dibujarnumeroMejor4(int x, int y);
    void dibujarnumeroMejor5(int x, int y);
    void dibujarnumeroMejor6(int x, int y);
    void dibujarnumeroMejor7(int x, int y);
    void dibujarnumeroMejor8(int x, int y);
    void dibujarnumeroMejor9(int x, int y);

    void borrarnumeroMejor0(int x, int y);
    void borrarnumeroMejor1(int x, int y);
    void borrarnumeroMejor2(int x, int y);
    void borrarnumeroMejor3(int x, int y);
    void borrarnumeroMejor4(int x, int y);
    void borrarnumeroMejor5(int x, int y);
    void borrarnumeroMejor6(int x, int y);
    void borrarnumeroMejor7(int x, int y);
    void borrarnumeroMejor8(int x, int y);
    void borrarnumeroMejor9(int x, int y);
    void borrarNumeros(int x, int y);

    void a(int x, int y);
    void b(int x, int y);
    void c(int x, int y);
    void d(int x, int y);
    void e(int x, int y);
    void f(int x, int y);
    void g(int x, int y);
    void h(int x, int y);
    void ii(int x, int y);
    void j(int x, int y);
    void k(int x, int y);
    void l(int x, int y);
    void m(int x, int y);
    void n(int x, int y);
    void o(int x, int y);
    void p(int x, int y);
    void q(int x, int y);
    void r(int x, int y);
    void s(int x, int y);
    void t(int x, int y);
    void u(int x, int y);
    void v(int x, int y);
    void w(int x, int y);
    void xx(int x, int y);
    void yy(int x, int y);
    void z(int x, int y);
    void coma(int x, int y);
    void puntoycoma(int x, int y);
    void dospuntos(int x, int y);
    void dospuntosGrande(int x, int y);
    void porcentaje(int x, int y);
    void admiracion(int x, int y);
    void punto(int x, int y);
    void guion(int x, int y);

    void textoPequenio(string tex, int x, int y);
    void textoGrande(string instruccion, int x, int y);
    void textoGrandeSinSleep(string instruccion, int x, int y);
    void textoPequenioSinSleep(string tex, int x, int y);
    void dibujarLlave(int x, int y);
    void dibujarMoldeLlave(int x, int y);
    void drawScreenTitle(int x, int y);
    void drawIniciarInput(int x, int y);
    void drawNivelesInput(int x, int y);
    void drawAyudaInput(int x, int y);
    void drawCreditosInput(int x, int y);
    void drawSalirInput(int x, int y);
    void drawScreenStart();
    void drawScreenNameTitle(int x, int y);
    int screenStart();
    int nivelesStart();
    void pantallaAyudaMision();
    void dibujarBarraStats(int x, int y, int vida, int MAX_STAT, string titulo, ConsoleColor color);
    void botonMenu(int x, int y);
    void dibujarCubetaAgua(int x, int y);
    void dibujarSemilla1(int x, int y);
    void dibujarSemilla2(int x, int y);
    void dibujarPapel(int x, int y);
    void dibujarBolsa(int x, int y);
    void dibujarCorazon(int x, int y);
    void borrarCorazon(int x, int y);
    void animateLoadingBar(int x, int y, int repeticiones, int tamanio);
    void dibujarCaracter(int x, int y, char caracter, ConsoleColor color);
    void dibujarNumeroPequenio(int numero, int x, int y);
    void sol(int x, int y);
    void arbusto(int x, int y);
    void arbol(int x, int y);
    void bloque1(int x, int y);
    void bloque2(int x, int y);
    void bloque3(int x, int y);
    void piso1(int x, int y, int longitud);
    void piso2(int x, int y, int longitud);
    void piso3(int x, int y, int longitud);
    void corazon(int x, int y);
    void aguilaxd1(int x, int y);
    void decoracion1();
    void lobo_perdedor(int x, int y);
    void lobo_ganador(int x, int y);
    void trofeo_perdedor(int x, int y);
    void trofeo_ganador(int x, int y);
    void estadisticas(int x, int y);
public:
    Grafico(Juego* juego);
    ~Grafico();
    void barraDeVida();
    void barraDeContaminacion();
    void chooseNameScreen();
    int pantallaInicio();
    int pantallaNiveles();
    void pantallaNivelesTexto();
    void pantallaAyuda();
    void pantallaCreditos();
    void pantallaSalir();
    void mostrarPantallaDeCarga();
    void mostrarPantallaGanador();
    void mostrarPantallaPerdedor();
    void mostrarEstadisticas();
    void volverMenuPrincipal();
    void mostrarMar(int x, int y);
    void mostrarMarContaminado(int alto, int ancho, int x, int y, int porcentajeContaminacion);
    void pantallaAyudaPersonajePrincipal();
    void pantallaAyudaRecursos();
    void dibujarNumero(int numero, int x, int y);
    void dibujarCorazones(int x, int y, int vidas);
    void mostrarContador(int& segundos, int x, int y, clock_t& inicio);
    void dibujarPlanta(int x, int y);
    void borrarPlanta(int x, int y);
    void mostrarContadoresRecursos();
    void pantallaPrimerNivel();
    void pantallaSegundoNivel();
    void pantallaTercerNivel();
    void pantalla_perdedor_xd1();
    void pantalla_ganador_xd1();
    Rectangle getRectangleMarRango();
    Rectangle getArbolesPlantarRango();
    Rectangle getArbolesPlantarArea();
};
